retriever:
  retriever_name: MedCPT
  corpus_name: Textbooks
  db_dir: ./corpus
  k: 5

llm:
  llm_name: OpenAI/gpt-3.5-turbo
  temperature: 0.0
  context_length: 15000

benchmark:
  scenario: standard
  n_docs: 5
  use_online_retrieval: false

datasets:
  - bioasq
  - pubmedqa
  - medqa
  - mmlu

output_dir: ./results/standard
